USE test_zespoly;
WITH CTE AS (
    SELECT MIN(PLACA_POD + COALESCE(PLACA_DOD, 0)) AS MINIMUM, 
        MAX(PLACA_POD + COALESCE(PLACA_DOD, 0)) AS MAXIMUM
    FROM PRACOWNICY
)
SELECT MINIMUM, MAXIMUM, (MAXIMUM - MINIMUM) AS ROZNICA
FROM CTE;