USE test_zespoly;
SELECT ID_ZESP, 
NAZWA, 
ADRES, 
(
    CASE 
        WHEN (ADRES LIKE 'PIOTRKOWSKA%') THEN 'SRODMIESCIE'
        WHEN (ADRES LIKE 'FABRYCZNA%') THEN 'WIDZEW'
        ELSE 'NIEZNANA'
    END
) AS DZIELNICA 
FROM ZESPOLY;