USE test_zespoly;
WITH CTE AS (
    SELECT DISTINCT YEAR(ZATRUDNIONY) AS 'ROK_ZATRUDNIENIA'
    FROM PRACOWNICY
)
SELECT ROK_ZATRUDNIENIA,
    (
        SELECT COUNT(ID_PRAC) 
        FROM PRACOWNICY
        WHERE YEAR(ZATRUDNIONY)=ROK_ZATRUDNIENIA
    ) AS 'ILOSC'
FROM CTE
GROUP BY ROK_ZATRUDNIENIA
ORDER BY ROK_ZATRUDNIENIA