USE test_zespoly;
WITH CTE AS (
    SELECT ID_ZESP, 
        COUNT(ID_PRAC) AS 'SUMA_PRACOWNIKOW'
    FROM PRACOWNICY
    GROUP BY ID_ZESP
)
SELECT * FROM CTE
WHERE SUMA_PRACOWNIKOW > 3
ORDER BY SUMA_PRACOWNIKOW DESC;