USE test_zespoly;
WITH CTE AS (
    SELECT ETAT, 
        (PLACA_POD + COALESCE(PLACA_DOD, 0)) AS 'PENSJA'
    FROM PRACOWNICY
)
SELECT DISTINCT ETAT,
    AVG(PENSJA) as 'SREDNIA_PENSJA'
FROM CTE
GROUP BY ETAT
ORDER BY SREDNIA_PENSJA DESC;